# --------------------------
# Load cleaned data
# --------------------------
source("cleaning_julius.R")  # creates casualties_long

# Required packages
library(shiny)
library(shinythemes)
library(tidyverse)
library(lubridate)
library(sf)
library(leaflet)
library(plotly)
library(DT)
library(rnaturalearth)

# --------------------------
# UI
# --------------------------
ui <- fluidPage(
  theme = shinytheme("cerulean"),
  titlePanel("Casualties Explorer — interactive Shiny app"),
  
  sidebarLayout(
    sidebarPanel(
      width = 3,
      
      helpText(
        strong("Data source:"),
        "Cleaned using cleaning_julius.R",
        br(),
        "Dataset: casualties_long"
      ),
      
      hr(),
      
      uiOutput("region_ui"),
      uiOutput("year_ui"),
      uiOutput("measure_ui"),
      uiOutput("group_ui"),
      
      selectInput(
        "plot_choice",
        "Chart type:",
        choices = c(
          "Time series",
          "Bar chart",
          "Stacked bar",
          "Heatmap (region x year)",
          "Scatter (two measures)",
          "Map"
        )
      ),
      
      radioButtons("agg", "Aggregation:", choices = c("sum", "mean", "count")),
      checkboxInput("show_region_labels", "Show region names on map", TRUE),
      hr(),
      downloadButton("download_csv", "Download filtered CSV")
    ),
    
    mainPanel(
      width = 9,
      tabsetPanel(
        tabPanel("Plot", plotlyOutput("main_plot", height = "650px")),
        tabPanel("Map", leafletOutput("map", height = "700px")),
        tabPanel("Table", DTOutput("table")),
        tabPanel("Metadata", verbatimTextOutput("meta"))
      )
    )
  )
)

# --------------------------
# Server
# --------------------------
server <- function(input, output, session){
  
  # Base data
  casualties <- reactive({
    casualties_long %>%
      rename_with(tolower)
  })
  
  # Detect region column
  region_col <- reactive({
    df <- casualties()
    cols <- names(df)[str_detect(
      names(df),
      regex("region|state|admin|name", ignore_case = TRUE)
    )]
    if (length(cols) > 0) cols[1] else NULL
  })
  
  # Numeric variables
  numeric_measures <- reactive({
    names(casualties())[sapply(casualties(), is.numeric)]
  })
  
  # ---------------- UI outputs ----------------
  output$region_ui <- renderUI({
    col <- region_col()
    if (!is.null(col)) {
      regs <- sort(unique(na.omit(casualties()[[col]])))
      selectizeInput("regions", "Regions:", regs, regs, multiple = TRUE)
    }
  })
  
  output$year_ui <- renderUI({
    df <- casualties()
    if ("date" %in% names(df)) {
      yrs <- year(df$date)
      sliderInput(
        "years",
        "Year range:",
        min(yrs, na.rm = TRUE),
        max(yrs, na.rm = TRUE),
        value = range(yrs, na.rm = TRUE),
        sep = ""
      )
    }
  })
  
  output$measure_ui <- renderUI({
    selectInput(
      "measure",
      "Measure:",
      numeric_measures(),
      numeric_measures()[1]
    )
  })
  
  output$group_ui <- renderUI({
    selectInput(
      "group_var",
      "Group (optional):",
      choices = c(None = "", names(casualties()))
    )
  })
  
  # ---------------- Filtered data ----------------
  filtered_data <- reactive({
    df <- casualties()
    col <- region_col()
    
    if (!is.null(col) && !is.null(input$regions))
      df <- df |> filter(.data[[col]] %in% input$regions)
    
    if ("date" %in% names(df) && !is.null(input$years))
      df <- df |> filter(
        year(date) >= input$years[1],
        year(date) <= input$years[2]
      )
    
    df
  })
  
  # ---------------- Table ----------------
  output$table <- renderDT({
    datatable(
      filtered_data(),
      options = list(
        pageLength = 25,
        scrollX = TRUE,
        autoWidth = TRUE
      )
    )
  })
  
  # ---------------- Metadata ----------------
  output$meta <- renderPrint({
    df <- casualties_long
    
    cat("DATA SOURCE\n")
    cat("-----------\n")
    cat("Generated by: cleaning_julius.R\n")
    cat("Object name: casualties_long\n\n")
    
    cat("DATASET DIMENSIONS\n")
    cat("------------------\n")
    cat("Rows:", nrow(df), "\n")
    cat("Columns:", ncol(df), "\n\n")
    
    cat("COLUMN NAMES\n")
    cat("------------\n")
    print(names(df))
    cat("\n")
    
    cat("MISSING VALUES PER COLUMN\n")
    cat("-------------------------\n")
    print(colSums(is.na(df)))
    cat("\n")
    
    cat("STRUCTURE\n")
    cat("---------\n")
    str(df)
  })
  
  # ---------------- Download ----------------
  output$download_csv <- downloadHandler(
    filename = function() {
      paste0("casualties_filtered_", Sys.Date(), ".csv")
    },
    content = function(file) {
      write_csv(filtered_data(), file)
    }
  )
}

shinyApp(ui, server)